### ISSUE TITLE
Docker Service - nginx

### ISSUE THREAD

**Issue by aseungbo** [aseungbo/42_Inception#4]
- [x] Nginx 수동 Build
- [x] Nginx DockerFile Build
- [x] docker-compose Build

**Comment by Jung-Off** [comment]
open ssl을 적용하는 부분에서

1. docker_container 내부에서 key를 생성하고 그 것을 이용해야하는건지
 - 컨테이너 내부에는 openssl을 위한 것이 아무것도 없음

2.로컬에서 받아서 그것을 이용을 해야하는 것인지

solve) 도컬파일 완성본을 보니 결국엔 내부에서 만들어서 사용하는 것 같다

**Comment by Jung-Off** [comment]
ssl_ciphers 여기 value에 무엇을 넣어주어야하는지 모르겠음
> 그래서 일단은 날리고 돌림

**Comment by Jung-Off** [comment]
nginx랑 openssl를 연결을 하니까 nginx첫 부분이 뜨지 않음!

**Comment by aseungbo** [comment]
> open ssl을 적용하는 부분에서
> 
> 1. docker_container 내부에서 key를 생성하고 그 것을 이용해야하는건지
> 
> * 컨테이너 내부에는 openssl을 위한 것이 아무것도 없음
> 
> 2.로컬에서 받아서 그것을 이용을 해야하는 것인지
> 
> solve) 도컬파일 완성본을 보니 결국엔 내부에서 만들어서 사용하는 것 같다

Dockerfile로 이미지를 만들 때, RUN apt-get install openssl -y 명령어를 사용하여 openssl을 설치하고 키 생성

**Comment by aseungbo** [comment]
> nginx랑 openssl를 연결을 하니까 nginx첫 부분이 뜨지 않음!

아마 nginx config에서 ssl 세팅을 안해서 그럴 수도? 어떻게 안 뜨는지 봐야알듯

**Comment by Jung-Off** [comment]
> 아마 nginx config에서 ssl 세팅을 안해서 그럴 수도? 어떻게 안 뜨는지 봐야알듯

이거 nginx부분만 가지고 와서? 돌려 본거 같은데 안된다고 오지게 뭐라함

**Comment by Jung-Off** [comment]
> 아마 nginx config에서 ssl 세팅을 안해서 그럴 수도? 어떻게 안 뜨는지 봐야알듯

ssl 파일 다 적용하고

docker build . -t nginx 로 이미지생성하고

docker run -d -it -p 80:80 -p 443:443 --name nginx nginx:latest
0d72c96ddcf486b48bdf7ad6de06beb81ac6dadfa85f83bac413a01aaa4b1699로
컨테이너 구동시키기! 
그러면 dockerfile로 ssl적용까지 끝!

**Comment by aseungbo** [comment]
> 

포트가 두 번 작성되는 건 2개 포트를 열겠다는 의미인가요?!

**Comment by Jung-Off** [comment]
80은 서브젝트에서 무시하라고 해서 443으로만 접근하면 될 것 같습니다요

**Comment by aseungbo** [comment]
https://velog.io/@aseungbo/42Inception nginx container
